#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intranet.ws.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Intranet")]
	public partial class IntranetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public IntranetDataContext() : 
				base(global::Intranet.ws.DataAccess.Properties.Settings.Default.IntranetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IntranetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IntranetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IntranetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IntranetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCountingEntities")]
		public ISingleResult<spCountingEntitiesResult> spCountingEntities()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spCountingEntitiesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerUsuario")]
		public ISingleResult<spObtenerUsuarioResult> spObtenerUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, pass);
			return ((ISingleResult<spObtenerUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerUsuarioFunciones")]
		public ISingleResult<spObtenerUsuarioFuncionesResult> spObtenerUsuarioFunciones([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID);
			return ((ISingleResult<spObtenerUsuarioFuncionesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spAgregarCiudades")]
		public int spAgregarCiudades([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MunicipioID", DbType="Int")] System.Nullable<int> municipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), municipioID, nombre, estadoID, activo, usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spAgregarCodigosPostales")]
		public int spAgregarCodigosPostales([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoPostal", DbType="VarChar(5)")] string codigoPostal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoAsentamiento", DbType="VarChar(30)")] string tipoAsentamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Asentamiento", DbType="VarChar(100)")] string asentamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zona", DbType="VarChar(100)")] string zona, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MunicipioID", DbType="Int")] System.Nullable<int> municipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CiudadId", DbType="Int")] System.Nullable<int> ciudadId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoPostal, tipoAsentamiento, asentamiento, zona, municipioID, ciudadId, activo, usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spAgregarEstados")]
		public int spAgregarEstados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(5)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaisID", DbType="Int")] System.Nullable<int> paisID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombre, paisID, usuarioID, activo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spAgregarMunicipios")]
		public int spAgregarMunicipios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(5)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombre, estadoID, activo, usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spAgregarPais")]
		public int spAgregarPais([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(2)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Moneda", DbType="VarChar(5)")] string moneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodMoneda", DbType="VarChar(3)")] string codMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, codigo, moneda, codMoneda, usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spEditarCiudades")]
		public int spEditarCiudades([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CiudadID", DbType="Int")] System.Nullable<int> ciudadID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MunicipioID", DbType="Int")] System.Nullable<int> municipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ciudadID, municipioID, nombre, estadoID, activo, usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spEditarCodigosPostales")]
		public int spEditarCodigosPostales([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoPostalID", DbType="Int")] System.Nullable<int> codigoPostalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoPostal", DbType="VarChar(5)")] string codigoPostal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoAsentamiento", DbType="VarChar(30)")] string tipoAsentamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Asentamiento", DbType="VarChar(100)")] string asentamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zona", DbType="VarChar(100)")] string zona, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MunicipioID", DbType="Int")] System.Nullable<int> municipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CiudadId", DbType="Int")] System.Nullable<int> ciudadId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoPostalID, codigoPostal, tipoAsentamiento, asentamiento, zona, municipioID, ciudadId, activo, usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spEditarEstados")]
		public int spEditarEstados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(5)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaisID", DbType="Int")] System.Nullable<int> paisID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estadoID, codigo, nombre, paisID, usuarioID, activo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spEditarMunicipios")]
		public int spEditarMunicipios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MunicipioID", DbType="Int")] System.Nullable<int> municipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(5)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), municipioID, codigo, nombre, estadoID, activo, usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spEditarPais")]
		public int spEditarPais([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaisID", DbType="Int")] System.Nullable<int> paisID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(2)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Moneda", DbType="VarChar(5)")] string moneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodMoneda", DbType="VarChar(3)")] string codMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paisID, nombre, codigo, moneda, codMoneda, usuarioID, activo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spObtenerMunicipios")]
		public ISingleResult<spObtenerMunicipiosResult> spObtenerMunicipios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MunicipioID", DbType="Int")] System.Nullable<int> municipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(5)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaisID", DbType="Int")] System.Nullable<int> paisID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), municipioID, codigo, nombre, estadoID, activo, paisID);
			return ((ISingleResult<spObtenerMunicipiosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spObtenerCiudades")]
		public ISingleResult<spObtenerCiudadesResult> spObtenerCiudades([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CiudadID", DbType="Int")] System.Nullable<int> ciudadID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MunicipioID", DbType="Int")] System.Nullable<int> municipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaisID", DbType="Int")] System.Nullable<int> paisID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ciudadID, municipioID, nombre, estadoID, activo, paisID);
			return ((ISingleResult<spObtenerCiudadesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spObtenerEstados")]
		public ISingleResult<spObtenerEstadosResult> spObtenerEstados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(5)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaisID", DbType="Int")] System.Nullable<int> paisID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estadoID, codigo, nombre, paisID, activo);
			return ((ISingleResult<spObtenerEstadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spObtenerCodigosPostales")]
		public ISingleResult<spObtenerCodigosPostalesResult> spObtenerCodigosPostales([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoPostal", DbType="VarChar(5)")] string codigoPostal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoAsentamiento", DbType="VarChar(30)")] string tipoAsentamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Asentamiento", DbType="VarChar(100)")] string asentamiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zona", DbType="VarChar(100)")] string zona, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MunicipioID", DbType="Int")] System.Nullable<int> municipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CiudadId", DbType="Int")] System.Nullable<int> ciudadId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoID", DbType="Int")] System.Nullable<int> estadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaisID", DbType="Int")] System.Nullable<int> paisID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoPostal, tipoAsentamiento, asentamiento, zona, municipioID, ciudadId, estadoID, activo, paisID);
			return ((ISingleResult<spObtenerCodigosPostalesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sepomex.spObtenerPaises")]
		public ISingleResult<spObtenerPaisesResult> spObtenerPaises([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(3)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaisID", DbType="Int")] System.Nullable<int> paisID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), activo, nombre, codigo, paisID);
			return ((ISingleResult<spObtenerPaisesResult>)(result.ReturnValue));
		}
	}
	
	public partial class spCountingEntitiesResult
	{
		
		private System.Nullable<int> _NoPaises;
		
		private System.Nullable<int> _NoEstados;
		
		private System.Nullable<int> _NoMunicipios;
		
		private System.Nullable<int> _NoCiudades;
		
		private System.Nullable<int> _NoCP;
		
		public spCountingEntitiesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoPaises", DbType="Int")]
		public System.Nullable<int> NoPaises
		{
			get
			{
				return this._NoPaises;
			}
			set
			{
				if ((this._NoPaises != value))
				{
					this._NoPaises = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoEstados", DbType="Int")]
		public System.Nullable<int> NoEstados
		{
			get
			{
				return this._NoEstados;
			}
			set
			{
				if ((this._NoEstados != value))
				{
					this._NoEstados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoMunicipios", DbType="Int")]
		public System.Nullable<int> NoMunicipios
		{
			get
			{
				return this._NoMunicipios;
			}
			set
			{
				if ((this._NoMunicipios != value))
				{
					this._NoMunicipios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCiudades", DbType="Int")]
		public System.Nullable<int> NoCiudades
		{
			get
			{
				return this._NoCiudades;
			}
			set
			{
				if ((this._NoCiudades != value))
				{
					this._NoCiudades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCP", DbType="Int")]
		public System.Nullable<int> NoCP
		{
			get
			{
				return this._NoCP;
			}
			set
			{
				if ((this._NoCP != value))
				{
					this._NoCP = value;
				}
			}
		}
	}
	
	public partial class spObtenerUsuarioResult
	{
		
		private int _UsuarioID;
		
		private string _Nombre;
		
		private int _RolID;
		
		private string _Rol;
		
		public spObtenerUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int NOT NULL")]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolID", DbType="Int NOT NULL")]
		public int RolID
		{
			get
			{
				return this._RolID;
			}
			set
			{
				if ((this._RolID != value))
				{
					this._RolID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
	}
	
	public partial class spObtenerUsuarioFuncionesResult
	{
		
		private int _UsuarioID;
		
		private int _RolID;
		
		private string _Rol;
		
		private int _FuncionID;
		
		private string _Funcion;
		
		private System.Nullable<int> _FuncionPadreID;
		
		private string _FuncionPadre;
		
		private string _FuncionDescripcion;
		
		private string _Url;
		
		public spObtenerUsuarioFuncionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int NOT NULL")]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolID", DbType="Int NOT NULL")]
		public int RolID
		{
			get
			{
				return this._RolID;
			}
			set
			{
				if ((this._RolID != value))
				{
					this._RolID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rol
		{
			get
			{
				return this._Rol;
			}
			set
			{
				if ((this._Rol != value))
				{
					this._Rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuncionID", DbType="Int NOT NULL")]
		public int FuncionID
		{
			get
			{
				return this._FuncionID;
			}
			set
			{
				if ((this._FuncionID != value))
				{
					this._FuncionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Funcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Funcion
		{
			get
			{
				return this._Funcion;
			}
			set
			{
				if ((this._Funcion != value))
				{
					this._Funcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuncionPadreID", DbType="Int")]
		public System.Nullable<int> FuncionPadreID
		{
			get
			{
				return this._FuncionPadreID;
			}
			set
			{
				if ((this._FuncionPadreID != value))
				{
					this._FuncionPadreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuncionPadre", DbType="VarChar(50)")]
		public string FuncionPadre
		{
			get
			{
				return this._FuncionPadre;
			}
			set
			{
				if ((this._FuncionPadre != value))
				{
					this._FuncionPadre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuncionDescripcion", DbType="VarChar(100)")]
		public string FuncionDescripcion
		{
			get
			{
				return this._FuncionDescripcion;
			}
			set
			{
				if ((this._FuncionDescripcion != value))
				{
					this._FuncionDescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(2000)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
	}
	
	public partial class spObtenerMunicipiosResult
	{
		
		private int _MunicipioID;
		
		private string _Codigo;
		
		private string _Nombre;
		
		private System.Nullable<int> _EstadoID;
		
		private System.Nullable<System.DateTime> _FechaUltimaModificacion;
		
		private System.Nullable<int> _UsuarioID;
		
		private System.Nullable<bool> _Activo;
		
		private string _Estado;
		
		private string _Pais;
		
		private int _PaisID;
		
		public spObtenerMunicipiosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioID", DbType="Int NOT NULL")]
		public int MunicipioID
		{
			get
			{
				return this._MunicipioID;
			}
			set
			{
				if ((this._MunicipioID != value))
				{
					this._MunicipioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(4)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(500)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoID", DbType="Int")]
		public System.Nullable<int> EstadoID
		{
			get
			{
				return this._EstadoID;
			}
			set
			{
				if ((this._EstadoID != value))
				{
					this._EstadoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUltimaModificacion
		{
			get
			{
				return this._FechaUltimaModificacion;
			}
			set
			{
				if ((this._FechaUltimaModificacion != value))
				{
					this._FechaUltimaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int")]
		public System.Nullable<int> UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(500)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(100)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this._Pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaisID", DbType="Int NOT NULL")]
		public int PaisID
		{
			get
			{
				return this._PaisID;
			}
			set
			{
				if ((this._PaisID != value))
				{
					this._PaisID = value;
				}
			}
		}
	}
	
	public partial class spObtenerCiudadesResult
	{
		
		private int _CiudadID;
		
		private string _Nombre;
		
		private System.Nullable<int> _EstadoID;
		
		private System.Nullable<int> _MunicipioID;
		
		private System.Nullable<System.DateTime> _FechaUltimaModificacion;
		
		private System.Nullable<int> _UsuarioID;
		
		private System.Nullable<bool> _Activo;
		
		private string _Municipio;
		
		private string _Estado;
		
		private string _Pais;
		
		private int _PaisID;
		
		public spObtenerCiudadesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiudadID", DbType="Int NOT NULL")]
		public int CiudadID
		{
			get
			{
				return this._CiudadID;
			}
			set
			{
				if ((this._CiudadID != value))
				{
					this._CiudadID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(500)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoID", DbType="Int")]
		public System.Nullable<int> EstadoID
		{
			get
			{
				return this._EstadoID;
			}
			set
			{
				if ((this._EstadoID != value))
				{
					this._EstadoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioID", DbType="Int")]
		public System.Nullable<int> MunicipioID
		{
			get
			{
				return this._MunicipioID;
			}
			set
			{
				if ((this._MunicipioID != value))
				{
					this._MunicipioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUltimaModificacion
		{
			get
			{
				return this._FechaUltimaModificacion;
			}
			set
			{
				if ((this._FechaUltimaModificacion != value))
				{
					this._FechaUltimaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int")]
		public System.Nullable<int> UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="VarChar(500)")]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(500)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(100)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this._Pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaisID", DbType="Int NOT NULL")]
		public int PaisID
		{
			get
			{
				return this._PaisID;
			}
			set
			{
				if ((this._PaisID != value))
				{
					this._PaisID = value;
				}
			}
		}
	}
	
	public partial class spObtenerEstadosResult
	{
		
		private int _EstadoID;
		
		private string _Codigo;
		
		private string _Nombre;
		
		private int _PaisID;
		
		private System.Nullable<System.DateTime> _FechaUltimaModificacion;
		
		private System.Nullable<int> _UsuarioID;
		
		private System.Nullable<bool> _Activo;
		
		private string _Pais;
		
		public spObtenerEstadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoID", DbType="Int NOT NULL")]
		public int EstadoID
		{
			get
			{
				return this._EstadoID;
			}
			set
			{
				if ((this._EstadoID != value))
				{
					this._EstadoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(5)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(500)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaisID", DbType="Int NOT NULL")]
		public int PaisID
		{
			get
			{
				return this._PaisID;
			}
			set
			{
				if ((this._PaisID != value))
				{
					this._PaisID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUltimaModificacion
		{
			get
			{
				return this._FechaUltimaModificacion;
			}
			set
			{
				if ((this._FechaUltimaModificacion != value))
				{
					this._FechaUltimaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int")]
		public System.Nullable<int> UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(100)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this._Pais = value;
				}
			}
		}
	}
	
	public partial class spObtenerCodigosPostalesResult
	{
		
		private int _CodigoPostalID;
		
		private string _CodigoPostal;
		
		private System.Nullable<int> _MunicipioID;
		
		private System.Nullable<int> _CiudadID;
		
		private string _Asentamiento;
		
		private string _TipoAsentamiento;
		
		private string _Zona;
		
		private System.Nullable<System.DateTime> _FechaUltimaModificacion;
		
		private System.Nullable<int> _UsuarioID;
		
		private System.Nullable<bool> _Activo;
		
		private string _Municipio;
		
		private string _Ciudad;
		
		private string _Estado;
		
		private int _EstadoID;
		
		private string _Pais;
		
		private int _PaisID;
		
		public spObtenerCodigosPostalesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostalID", DbType="Int NOT NULL")]
		public int CodigoPostalID
		{
			get
			{
				return this._CodigoPostalID;
			}
			set
			{
				if ((this._CodigoPostalID != value))
				{
					this._CodigoPostalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="NVarChar(255)")]
		public string CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this._CodigoPostal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioID", DbType="Int")]
		public System.Nullable<int> MunicipioID
		{
			get
			{
				return this._MunicipioID;
			}
			set
			{
				if ((this._MunicipioID != value))
				{
					this._MunicipioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiudadID", DbType="Int")]
		public System.Nullable<int> CiudadID
		{
			get
			{
				return this._CiudadID;
			}
			set
			{
				if ((this._CiudadID != value))
				{
					this._CiudadID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asentamiento", DbType="NVarChar(255)")]
		public string Asentamiento
		{
			get
			{
				return this._Asentamiento;
			}
			set
			{
				if ((this._Asentamiento != value))
				{
					this._Asentamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoAsentamiento", DbType="NVarChar(255)")]
		public string TipoAsentamiento
		{
			get
			{
				return this._TipoAsentamiento;
			}
			set
			{
				if ((this._TipoAsentamiento != value))
				{
					this._TipoAsentamiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zona", DbType="NVarChar(255)")]
		public string Zona
		{
			get
			{
				return this._Zona;
			}
			set
			{
				if ((this._Zona != value))
				{
					this._Zona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUltimaModificacion
		{
			get
			{
				return this._FechaUltimaModificacion;
			}
			set
			{
				if ((this._FechaUltimaModificacion != value))
				{
					this._FechaUltimaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int")]
		public System.Nullable<int> UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="VarChar(500)")]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(500)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(500)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoID", DbType="Int NOT NULL")]
		public int EstadoID
		{
			get
			{
				return this._EstadoID;
			}
			set
			{
				if ((this._EstadoID != value))
				{
					this._EstadoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(100)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this._Pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaisID", DbType="Int NOT NULL")]
		public int PaisID
		{
			get
			{
				return this._PaisID;
			}
			set
			{
				if ((this._PaisID != value))
				{
					this._PaisID = value;
				}
			}
		}
	}
	
	public partial class spObtenerPaisesResult
	{
		
		private int _PaisID;
		
		private string _Nombre;
		
		private string _Codigo;
		
		private string _Moneda;
		
		private string _CodMoneda;
		
		private System.Nullable<System.DateTime> _FechaUltimaModificacion;
		
		private System.Nullable<int> _UsuarioID;
		
		private System.Nullable<bool> _Activo;
		
		public spObtenerPaisesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaisID", DbType="Int NOT NULL")]
		public int PaisID
		{
			get
			{
				return this._PaisID;
			}
			set
			{
				if ((this._PaisID != value))
				{
					this._PaisID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this._Moneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodMoneda", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CodMoneda
		{
			get
			{
				return this._CodMoneda;
			}
			set
			{
				if ((this._CodMoneda != value))
				{
					this._CodMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaUltimaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaUltimaModificacion
		{
			get
			{
				return this._FechaUltimaModificacion;
			}
			set
			{
				if ((this._FechaUltimaModificacion != value))
				{
					this._FechaUltimaModificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int")]
		public System.Nullable<int> UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this._UsuarioID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit")]
		public System.Nullable<bool> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
